name: CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
#  workflow_run:
#    workflows: [golangci-lint]
#    types: [completed]
    
#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  unit-test:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: Unit-test
      run: make test

  e2e-tests:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: e2e-tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      IMAGE_REGISTRY: kind-registry:5000
      KIND_VERSION: v0.18.0
      K8S_VERSION: v1.26.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          
      - name: Start kind cluster
        uses: container-tools/kind-action@v2
        with:
          cluster_name: hub
          version: ${{env.KIND_VERSION}}
          node_image: kindest/node:${{env.K8S_VERSION}}
          kubectl_version: ${{env.K8S_VERSION}}
          registry: true

      - name: Start kind cluster
        uses: container-tools/kind-action@v2
        with:
          cluster_name: cluster1
          version: ${{env.KIND_VERSION}}
          node_image: kindest/node:${{env.K8S_VERSION}}
          kubectl_version: ${{env.K8S_VERSION}}
          registry: false

      - name: Start kind cluster
        uses: container-tools/kind-action@v2
        with:
          cluster_name: cluster2
          version: ${{env.KIND_VERSION}}
          node_image: kindest/node:${{env.K8S_VERSION}}
          kubectl_version: ${{env.K8S_VERSION}}
          registry: false

      - name: Build rcs-ocm-deployer image
        run: make docker-build docker-push IMG=${IMAGE_REGISTRY}/rcs-ocm-deployer:test-${GITHUB_REF##*/}

      - name: Setup rcs environment
        run: make ci-quickstart IMG=${IMAGE_REGISTRY}/rcs-ocm-deployer:test-${GITHUB_REF##*/}

      - name: Deploy to rcs cluster
        run: make deploy deploy-addon IMG=${IMAGE_REGISTRY}/rcs-ocm-deployer:test-${GITHUB_REF##*/}

      - name: Await rcs
        uses: jupyterhub/action-k8s-await-workloads@v2
        with:
          workloads: ""
          namespace: "rcs-deployer-system"
          timeout: 60
          max-restarts: 0

      - name: Run e2e test
        run: make test-e2e
